#
MYSQL_DATABASE=cursos
MYSQL_USER=MainUser
MYSQL_ROOT_PASSWORD=RootPassword
MYSQL_PASSWORD=MainPassword
MYSQL_HOST=desafio1fca-mysql-host
NODEJS_HOST=desafio1fca-nodejs-host 
NGINX_HOST=desafio1fca-nginx-host 
NODEJS_PORT=8000
MYSQL_PORT=3306
DOCKER_NET=desafio1fca-net
DOCKER_MYSQL_CONTAINER_NAME=desafio1fca-mysql-container
DOCKER_NODEJS_CONTAINER_NAME=desafio1fca-nodejs-container
DOCKER_NGINX_CONTAINER_NAME=desafio1fca-nginx-container
#
docker network create desafio1fca-net
docker rm $DOCKER_MYSQL_CONTAINER_NAME
docker rm $DOCKER_NODEJS_CONTAINER_NAME
docker rm $DOCKER_NGINX_CONTAINER_NAME
docker run -d --network=$DOCKER_NET --name=$DOCKER_MYSQL_CONTAINER_NAME --hostname $MYSQL_HOST -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD -e MYSQL_DATABASE=$MYSQL_DATABASE -e MYSQL_USER=$MYSQL_USER -e MYSQL_PASSWORD=$MYSQL_PASSWORD alvieirajr/desafio1fca-mysql
docker run -d --network=$DOCKER_NET --name=$DOCKER_NODEJS_CONTAINER_NAME --hostname $NODEJS_HOST -e MYSQL_PORT=$MYSQL_PORT -e NODEJS_PORT=$NODEJS_PORT -e MYSQL_HOST=$MYSQL_HOST -e MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD -e MYSQL_DATABASE=$MYSQL_DATABASE -e MYSQL_USER=$MYSQL_USER -e MYSQL_PASSWORD=$MYSQL_PASSWORD alvieirajr/desafio1fca-nodejs
docker run -d --network=$DOCKER_NET --name=$DOCKER_NGINX_CONTAINER_NAME --hostname $NGINX_HOST -p 8080:80 -e NODEJS_HOST=$NODEJS_HOST -e NGINX_HOST=$NGINX_HOST -e NODEJS_PORT=$NODEJS_PORT alvieirajr/desafio1fca-nginx
