FROM node

WORKDIR /usr/src/app
RUN apt-get update \
    && apt-get install -y default-mysql-client

COPY . .

RUN npm install 

EXPOSE ${NODEJS_PORT}

RUN chmod +x /usr/src/app/wait-and-go.sh

CMD ["/usr/src/app/wait-and-go.sh"]

#CMD [ "bash" ]